inputs:
  github-token:
    description: 'Github token to post jacoco report in PR comment'
    required: true
runs:
  using: "composite"
  steps:

    - name: jacocoTestReportDebug-clevertap-core
      if: always()
      shell: bash
      run: ./gradlew :clevertap-core:jacocoTestReportDebug  -Pcoverage='true'

    - name: Upload1
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: TestReportDebug-clevertap-core
        path: clevertap-core/build/reports/tests

    - name: Upload2
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: JacocoReportDebug-clevertap-core
        path: clevertap-core/build/reports/jacoco


    #-----#----------#----------#----------#----------#----------#----------#----------#----------#----------#----------#----------#----------#-----
    - name: jacocoTestReportDebug-clevertap-geofence
      if: always()
      shell: bash
      run: ./gradlew :clevertap-geofence:jacocoTestReportDebug  -Pcoverage='true'

    - name: Upload1
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: TestReportDebug-clevertap-geofence
        path: clevertap-geofence/build/reports/tests

    - name: Upload2
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: JacocoReportDebug-clevertap-geofence
        path: clevertap-geofence/build/reports/jacoco


    #-----#----------#----------#----------#----------#----------#----------#----------#----------#----------#----------#----------#----------#-----
    - name: jacocoTestReportDebug-clevertap-hms
      if: always()
      shell: bash
      run: ./gradlew :clevertap-hms:jacocoTestReportDebug  -Pcoverage='true'

    - name: Upload1
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: TestReportDebug-clevertap-hms
        path: clevertap-hms/build/reports/tests

    - name: Upload2
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: JacocoReportDebug-clevertap-hms
        path: clevertap-hms/build/reports/jacoco



    #-----#----------#----------#----------#----------#----------#----------#----------#----------#----------#----------#----------#----------#-----
    - name: jacocoTestReportDebug-clevertap-pushtemplates
      if: always()
      shell: bash
      run: ./gradlew :clevertap-pushtemplates:jacocoTestReportDebug  -Pcoverage='true'

    - name: Upload1
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: TestReportDebug-clevertap-pushtemplates
        path: clevertap-pushtemplates/build/reports/tests

    - name: Upload2
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: JacocoReportDebug-clevertap-pushtemplates
        path: clevertap-pushtemplates/build/reports/jacoco

    - name: JacocoGithubReport
      uses: madrapps/jacoco-report@v1.7.1
      with:
          paths: |
            clevertap-core/build/reports/jacoco/jacocoTestReportDebug/jacocoTestReportDebug.xml,
            clevertap-geofence/build/reports/jacoco/jacocoTestReportDebug/jacocoTestReportDebug.xml,
            clevertap-hms/build/reports/jacoco/jacocoTestReportDebug/jacocoTestReportDebug.xml,
            clevertap-pushtemplates/build/reports/jacoco/jacocoTestReportDebug/jacocoTestReportDebug.xml
          token: ${{ inputs.github-token }}
          min-coverage-overall: 75
          min-coverage-changed-files: 75
          title: Code Coverage
          update-comment: true
          pass-emoji: ':green_circle:'
          fail-emoji: ':red_circle:'


    - name: Setup .NET Core # Required to execute ReportGenerator
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x
        dotnet-quality: 'ga'

    - name: ReportGenerator
      uses: danielpalme/ReportGenerator-GitHub-Action@5.4.5
      with:
        reports: 'clevertap-core/build/reports/jacoco/jacocoTestReportDebug/jacocoTestReportDebug.xml;clevertap-geofence/build/reports/jacoco/jacocoTestReportDebug/jacocoTestReportDebug.xml;clevertap-hms/build/reports/jacoco/jacocoTestReportDebug/jacocoTestReportDebug.xml;clevertap-pushtemplates/build/reports/jacoco/jacocoTestReportDebug/jacocoTestReportDebug.xml' # REQUIRED # The coverage reports that should be parsed (separated by semicolon). Globbing is supported.
        targetdir: 'coveragereport' # REQUIRED # The directory where the generated report should be saved.
        reporttypes: 'MarkdownSummaryGithub'
        verbosity: 'Warning' # The verbosity level of the log messages. Values: Verbose, Info, Warning, Error, Off
        title: 'Code Coverage' # Optional title.
        toolpath: 'reportgeneratortool' # Default directory for installing the dotnet tool.

    - name: Add comment to PR # Only applicable if 'MarkdownSummaryGithub' or one of the other Markdown report types is generated
      if: github.event_name == 'pull_request'
      run: gh pr comment $PR_NUMBER --body-file coveragereport/SummaryGithub.md # Adjust path and filename if necessary
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        PR_NUMBER: ${{ github.event.number }}

    - name: Publish coverage in build summary # Only applicable if 'MarkdownSummaryGithub' or one of the other Markdown report types is generated
      run: cat coveragereport/SummaryGithub.md >> $GITHUB_STEP_SUMMARY # Adjust path and filename if necessary
      shell: bash
